# Generated by Django 5.2 on 2025-05-06 20:45

import django.core.validators
import django.db.models.deletion
import insurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=insurance.models.generate_customer_id, max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_national_code', message='کد ملی باید 10 رقم باشد', regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='شماره تماس باید با 09 شروع شود و 11 رقم باشد', regex='^09\\d{9}$')], verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد شرکت')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='آدرس لوگو')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب سایت رسمی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'شرکت بیمه',
                'verbose_name_plural': 'شرکت های بیمه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع بیمه')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد نوع بیمه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع بیمه',
                'verbose_name_plural': 'انواع بیمه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پوشش')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد پوشش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت پایه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='insurance.insurancetype', verbose_name='نوع بیمه')),
            ],
            options={
                'verbose_name': 'پوشش بیمه',
                'verbose_name_plural': 'پوشش های بیمه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_number', models.CharField(default=insurance.models.generate_policy_number, max_length=20, primary_key=True, serialize=False, verbose_name='شماره بیمه نامه')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضاء')),
                ('premium_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ حق بیمه')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی شده'), ('canceled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('coverages', models.ManyToManyField(related_name='policies', to='insurance.coverage', verbose_name='پوشش ها')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.customer', verbose_name='مشتری')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.insurancecompany', verbose_name='شرکت بیمه')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.insurancetype', verbose_name='نوع بیمه')),
            ],
            options={
                'verbose_name': 'بیمه نامه',
                'verbose_name_plural': 'بیمه نامه ها',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Annex',
            fields=[
                ('annex_number', models.CharField(default=insurance.models.generate_annex_number, max_length=20, primary_key=True, serialize=False, verbose_name='شماره الحاقیه')),
                ('description', models.TextField(verbose_name='شرح تغییرات')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('additional_premium', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حق بیمه اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('coverages_added', models.ManyToManyField(blank=True, related_name='annexes_added', to='insurance.coverage', verbose_name='پوشش های اضافه شده')),
                ('coverages_removed', models.ManyToManyField(blank=True, related_name='annexes_removed', to='insurance.coverage', verbose_name='پوشش های حذف شده')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexes', to='insurance.policy', verbose_name='بیمه نامه')),
            ],
            options={
                'verbose_name': 'الحاقیه',
                'verbose_name_plural': 'الحاقیه ها',
                'ordering': ['-issue_date'],
            },
        ),
    ]
