# Generated by Django 5.2 on 2025-05-05 07:28

import EducationApp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد رشته')),
                ('name', models.CharField(max_length=100, verbose_name='نام رشته')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تاسیس')),
                ('total_credits', models.PositiveIntegerField(default=0, verbose_name='تعداد کل واحدها')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'رشته\u200cهای تحصیلی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد دانشکده')),
                ('name', models.CharField(max_length=100, verbose_name='نام دانشکده')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تاسیس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دانشکده',
                'verbose_name_plural': 'دانشکده\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True, verbose_name='کد درس')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان درس')),
                ('credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='تعداد واحد')),
                ('is_practical', models.BooleanField(default=False, verbose_name='عملی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('prerequisites', models.ManyToManyField(blank=True, to='EducationApp.course', verbose_name='پیش\u200cنیازها')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.department', verbose_name='رشته تحصیلی')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'ordering': ['department__name', 'title'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.faculty', verbose_name='دانشکده'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[EducationApp.models.validate_national_code], verbose_name='کد ملی')),
                ('birth_certificate_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل تولد')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'مجرد'), ('M', 'متاهل'), ('D', 'مطلقه'), ('W', 'بیوه')], max_length=1, null=True, verbose_name='وضعیت تاهل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_photos/', verbose_name='عکس')),
                ('professor_code', models.CharField(max_length=10, unique=True, verbose_name='کد استادی')),
                ('academic_rank', models.CharField(blank=True, max_length=50, null=True, verbose_name='مرتبه علمی')),
                ('contract_type', models.CharField(choices=[('FT', 'تمام وقت'), ('PT', 'پاره وقت'), ('I', 'حق التدریس')], max_length=2, verbose_name='نوع قرارداد')),
                ('employment_date', models.DateField(verbose_name='تاریخ استخدام')),
                ('education_level', models.CharField(max_length=50, verbose_name='مدرک تحصیلی')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='تخصص')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.department', verbose_name='رشته تحصیلی')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.CreateModel(
            name='ClassOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20, verbose_name='کد کلاس')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.course', verbose_name='درس')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.professor', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['semester', 'course__title'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='شماره اتاق')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('has_projector', models.BooleanField(default=False, verbose_name='دارای ویدیو پروژکتور')),
                ('floor', models.PositiveIntegerField(verbose_name='طبقه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.faculty', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
                'ordering': ['faculty__name', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('class_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.classoffering', verbose_name='کلاس')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'جلسه کلاس',
                'verbose_name_plural': 'جلسات کلاس',
                'ordering': ['class_offering', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(verbose_name='سال تحصیلی')),
                ('semester_type', models.CharField(choices=[('F', 'پاییز'), ('S', 'بهار')], max_length=1, verbose_name='نیمسال')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='ترم فعال')),
            ],
            options={
                'verbose_name': 'ترم تحصیلی',
                'verbose_name_plural': 'ترم\u200cهای تحصیلی',
                'ordering': ['-academic_year', '-semester_type'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'semester_type'), name='unique_semester')],
            },
        ),
        migrations.AddField(
            model_name='classoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.semester', verbose_name='ترم'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[EducationApp.models.validate_national_code], verbose_name='کد ملی')),
                ('birth_certificate_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل تولد')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'مجرد'), ('M', 'متاهل'), ('D', 'مطلقه'), ('W', 'بیوه')], max_length=1, null=True, verbose_name='وضعیت تاهل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_photos/', verbose_name='عکس')),
                ('student_code', models.CharField(max_length=10, unique=True, verbose_name='شماره دانشجویی')),
                ('admission_date', models.DateField(verbose_name='تاریخ پذیرش')),
                ('military_status', models.CharField(blank=True, choices=[('S', 'در حال خدمت'), ('E', 'معاف'), ('F', 'به پایان رسیده'), ('P', 'معافیت تحصیلی'), ('N', 'مشمول')], max_length=1, null=True, verbose_name='وضعیت نظام وظیفه')),
                ('student_status', models.CharField(choices=[('AC', 'فعال'), ('ON', 'مرخصی'), ('GR', 'فارغ التحصیل'), ('EX', 'اخراج'), ('WT', 'انصراف')], default='AC', max_length=2, verbose_name='وضعیت دانشجویی')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='تاریخ فارغ\u200cالتحصیلی')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.department', verbose_name='رشته تحصیلی')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجویان',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('status', models.CharField(choices=[('P', 'در انتظار تایید'), ('A', 'تایید شده'), ('R', 'رد شده'), ('D', 'حذف شده')], default='P', max_length=1, verbose_name='وضعیت')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره')),
                ('class_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.classoffering', verbose_name='کلاس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationApp.student', verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه شخص')),
                ('contact_type', models.CharField(choices=[('M', 'موبایل'), ('H', 'منزل'), ('W', 'محل کار'), ('O', 'سایر')], max_length=1, verbose_name='نوع تماس')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('is_primary', models.BooleanField(default=False, verbose_name='اصلی')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع شخص')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='EducationAp_content_f09032_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('room_number', 'faculty'), name='unique_room_number_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='check_session_times'),
        ),
        migrations.AddConstraint(
            model_name='classoffering',
            constraint=models.UniqueConstraint(fields=('course', 'semester', 'class_code'), name='unique_class_offering'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'class_offering'), name='unique_enrollment'),
        ),
    ]
